### ISSUE TITLE
Offsets

### ISSUE THREAD

**Issue by Zordon1337** [rdbo/Half-Life-2-Multihack#2]
i have question, how did you got the HL2 Offsets?

**Comment by rdbo** [comment]
I reverse engineered the game myself using Cheat Engine (I think Ghidra also)

**Comment by Zordon1337** [comment]
thanks

**Comment by Zordon1337** [comment]
Hello i have another question, do you know any tutorial how get offsets with ghidra, i tried ida but i can't understand tutorials for ida

**Comment by rdbo** [comment]
Easiest way to get offsets in HL2 is using Cheat Engine. Find the health, see what accesses it, get the offset from the local player object, ...
Ghidra is for static analysis, for example, you found an interesting function in Cheat Engine and now you want to take a deeper look at it (at least that's how I used it most of the time), not really for getting offsets

**Comment by Zordon1337** [comment]
But how to get Fov offset for ex.

**Comment by rdbo** [comment]
There is a command in the developer console that allows you to change the FOV (I don't really remember it, but it exists). If you can change the FOV, you can filter down the values on Cheat Engine and get to the FOV address.

**Comment by Zordon1337** [comment]
Viewmodel_fov? Or smth like this

**Comment by rdbo** [comment]
viewmodel_fov is for the FOV of the players hand, not the actual FOV. But there is a command for actual FOV IIRC.
